### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by RogerSi666** [RogerSi666/furima-38008#23]
# URL
https://furima-38008.herokuapp.com/

# Basic認証のIDとパスワード
admin
password: 2222

# 出品者用のメールアドレスとパスワード　
email: test@test1.com
password: testtest12

# 購入者用のメールアドレスとパスワード
email: test@test2.com
password: testtest12

**Comment by motomuun** [comment]
@RogerSi666 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品編集機能の確認**

- [x] **ページ下部の「もどる」ボタンを押すと、編集途中の情報は破棄され、商品詳細表示ページに遷移すること**
現状トップページに遷移しますので、詳細ページに遷移するように修正をお願いします。

- [x] **ログイン状態の場合でも、自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
売却済み商品の商品編集ページへ遷移できてしまいます。
たとえ自身が出品した商品であっても、売却済み商品の商品編集ページへは遷移できず、トップページに遷移するように修正をお願い致します。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by RogerSi666** [comment]
レビューありがとうございます

**Comment by motomuun** [comment]
@RogerSi666 さん、再度ご提出いただきありがとうございます‼︎
動作の確認をしたところ、前回の指摘点について修正が確認できませんでした。
マージやデプロイ忘れの可能性もございます。
今一度、以下のご確認をお願い致します！

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shodai-ito** [comment]
@RogerSi666 さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した最終課題ガイダンス資料にてご確認いただきますようお願いいたします。

＜最終課題ガイダンス資料の再確認＞
最終課題フェーズに入る直前に確認いただいた資料と同じものですが、必ず確認の上、次の学習に取り組みましょう。
とりわけ、資料の「3. 悩んだ際のアクション」については、改めてよく確認するようにしてください。
https://master.tech-camp.in/v2/curriculums/7681

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題LGTM](https://user-images.githubusercontent.com/62537107/191675908-06c888c3-d451-4e2c-b39e-c9d0a71f5e41.png)

**Comment by RogerSi666** [comment]
ありがとうございました！
